Applications/Home/urls.py
from django.urls import path
from Applications.Home import views

app_name = 'Home-app'
urlpatterns = [
    path('Home/', views.Home.as_view(), name='Home'),
    path('editar-home/<pk>/', views.EditContentHome.as_view(), name='EditContentHome'),
]

Applications/gallery/urls.py
from Applications.gallery import views
from django.urls import path


from Applications.gallery.views import GalleryThreatSection


app_name = 'gallery-app'
urlpatterns =[
    path('ListaPhotos/', views.GallerySection.as_view(), name='ListaPhotos'),
    path('Amenazas/', views.GalleryThreatSection.as_view(), name='amenazas'),
    path('updateThreat/<pk>/',views.ThreatUpdate.as_view(), name='modifyThreat'),
    path('vistasFlora',views.vistasFloraFauna.as_view(), name='vistasFlora'),
]

Web_Humedal_Culebron/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #Locals paths
    re_path('',include('Applications.Home.urls')),
    re_path('',include('Applications.gallery.urls'))
]

Applications/Home/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Content_Blocks(models.Model):
    Name = models.CharField(max_length=100)
    Option_section = (
        ('0', 'Home'),
        ('1', 'Galeria'),
        ('2', 'Noticias'),
        ('3', 'Recursos'),
        ('4', 'Reservas'),
    )
    Section = models.CharField('Seccion', max_length=2, choices=Option_section)
    Body = RichTextField(blank=True, null=True)

Applications/gallery/models.py
from ckeditor.fields import RichTextField
from django.db import models

# Create your models here.

class Photos(models.Model):
    name = models.CharField('nombre',max_length=30)
    photo = models.ImageField('img',upload_to='static/photos')
    description = models.TextField('descripcion', blank=True)
    Option_section = (
        ('0','general'),
        ('1', 'biodiversidad'),
        ('2', 'actividades'),
        ('3', 'amenazas'),
        ('4','flora')
    )
    Section= models.CharField('Seccion', max_length=2, choices=Option_section, blank=True)

    def __str__(self):
        return str(self.photo) + ' ' + str(self.Section)


class GallerySubSection(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return str(self.id) + ' ' + self.name


class Danger(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='static/dangerPhotos')


    def __str__(self):
        return self.title

class SectionFauna(models.Model):
    title = models.CharField('titulo',max_length=50)
    description = models.TextField('descripcion')
    photo = models.ImageField('img',upload_to='static/faunaPhotos')

    def __str__(self):
        return self.title

Applications/Home/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (ListView, DetailView, UpdateView)
from .models import *

# Create your views here.
class Home(ListView):
    model = Content_Blocks
    template_name = 'Home/home.html'
    context_object_name = 'content_blocks'

    def get_queryset(self):
        list_blocks = Content_Blocks.objects.filter(
            Section='0'
        )
        return list_blocks

class EditContentHome(UpdateView):
    model = Content_Blocks
    template_name = 'Home/editar_Home.html'
    context_object_name = 'content_blocks'
    fields = ['Body']
    success_url = reverse_lazy('Home-app:Home')

'''class Block_View(DetailView):
    model = Content_Blocks
    template_name = 'Home/Block_Detail.html'
    context_object_name = 'Block_Detail'''

Applications/gallery/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ( ListView,
                                   UpdateView )

    
from .models import Photos, Danger, SectionFauna



# Create your views here.

class GallerySection(ListView):
    model = Photos
    template_name = 'gallery/galleryPhotos.html'
    context_object_name = 'photos_gallery'

class GalleryThreatSection(ListView):
    model = Photos
    template_name = 'gallery/amenazas.html'
    context_object_name = 'photos_gallery'

class ThreatUpdate(UpdateView):
    model = Danger
    template_name = 'gallery/amenazasUpdate.html'
    context_object_name = 'infoUpdateAmenaza'
    fields = ['title', 'description']

class vistasFloraFauna(ListView):
    model = SectionFauna
    template_name = 'gallery/galleryPhotos.html'
    context_object_name = 'floraView'

templates/Home/Block_Detail.html
{% extends 'base.html'%}

{% block content %}

    

{% endblock %}

templates/Home/List_All_Blocks.html
{% extends 'base.html'%}

{% block content %}

    

{% endblock %}

templates/Home/editar_Home.html
{% extends 'base.html' %}

{% block content %}


    <main class="container py-5" >
        <section class="card card-body">
            <h1 class="display-1 text-center mi-estilo">Editar Contenido</h1>
            <form method="post"  class="container-fluid border p-4 rounded">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p }}
                <div class="text-center">
                    <button type="submit" class="btn btn-dark">Actualizar Seccion</button>
                </div>
            </form>
        </section>
    </main>

{% endblock %}

templates/Home/home.html
{% extends 'base.html' %}

{% block content %}
    <main class="container py-5">
        <section class="card card-body">
            <div>
                {% for block in content_blocks %}
                  <div class="content-block">
                    <div class="body-content">
                      {{ block.Body|safe }}
                    </div>
                  </div>
                    <div class="text-center">
                        <a href="{% url 'Home-app:EditContentHome' block.id %}" class="btn btn-dark">Editar</a>
                    </div>
                {% endfor %}
            </div>
            
        </section>
    </main>
{% endblock %}

templates/base.html
{% load static %} <!-- Cargar la etiqueta static de Django -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Django CRUD Aplication</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success navbar-dark">
        <div class="container">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a href="{% url 'Home-app:Home'%}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link">¿Quienes somos?</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Proyectos</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Recursos</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Noticias</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Actividades/Reservas</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Linea del tiempo</a></li>
                <li class="nav-item"><a href="#" class="nav-link">Contacto</a></li>

            </ul>
          </div>
        </div>
      </nav>

    {% block content %}
    {% endblock %}

</body>
</html>

templates/gallery/amenazas.html
{% extends 'base.html'%}

{% block content %}
{% load static %}

<div class="col-10 d-flex justify-content-center " style="width: 100%">
    <div >
        <h1 style="color: #198754" >Amenazas</h1>
    </div>
</div>

<div class="container">

    <div class="card">
    <a href="" style="text-decoration: none">
        <img style="width: 100%" class="img-fluid" src="{% static "photos/1.png" %}" alt="{{ img.title }}">
            <div class="card-content">
                <h3 class="card-title" style="color: #198754" >Amenaza1</h3>
                <p style="text-decoration: none" class="card-description"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto, in mollitia necessitatibus quis reprehenderit sequi tempore unde vitae! Aspernatur beatae culpa cum in itaque iure minima necessitatibus, neque praesentium rem.</p>
        </div>
    </a>
    </div>

      <div class="card">
    <a href="" style="text-decoration: none">
        <img style="width: 100%" class="img-fluid" src="{% static "photos/2.png" %}" alt="{{ img.title }}">
            <div class="card-content">
                <h3 class="card-title" style="color: #198754" >Amenaza2</h3>
                <p style="text-decoration: none" class="card-description"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto, in mollitia necessitatibus quis reprehenderit sequi tempore unde vitae! Aspernatur beatae culpa cum in itaque iure minima necessitatibus, neque praesentium rem.</p>
        </div>
    </a>
    </div>

  <div class="card">
    <a href="" style="text-decoration: none">
        <img style="width: 100%" class="img-fluid" src="{% static "photos/3.png" %}" alt="{{ img.title }}">
            <div class="card-content">
                <h3 class="card-title" style="color: #198754" >Amenaza3</h3>
                <p style="text-decoration: none" class="card-description"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto, in mollitia necessitatibus quis reprehenderit sequi tempore unde vitae! Aspernatur beatae culpa cum in itaque iure minima necessitatibus, neque praesentium rem.</p>
        </div>
    </a>
    </div>
</div>


{% endblock %}

templates/gallery/amenazasUpdate.html
{% extends 'base.html'%}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Actualizar</button>
</form>

{% endblock %}

templates/gallery/galleryPhotos.html
{% extends 'base.html'%}


{% block content %}

{% load static %}

    <div class="col-10 d-flex justify-content-center " style="width: 100%">
    <div >
        <h1 style="color: #198754 ;margin-top: 50px" >Galeria</h1>
    </div>
    </div>

    <div class="container" style="width: 100%">
    <div class="col-10 d-flex justify-content-center  mt-4" style="width: 100%" >
            <div class="gallery d-block " style="width: 100%">
                    {% for img in photos_gallery %}
                         {% if img.Section == '0' %}
                             <img style="width: 33%" class="gallery-item" src="{{ img.photo.url }}" alt="{{ img.title }}">
                         {% endif %}
                    {% endfor %}
            </div>
    </div>
    </div>

    <div class="container" style="width: 100%" >
    <div class="col-10 justify-content-center  mt-4" style="width: 100%" >
        <div class="subSecciones" style="margin-top: 30px;">
            <div style="margin-bottom: 20px;">
            <a href="#" class="btn-Sub">Biodiversidad</a>
            <p style="margin-top: 10px;font-weight: 700;">Descubre la diversidad del humedal</p>
            </div>
                <div class="d-flex justify-content-between">
                    {% for img in photos_gallery %}
                         {% if img.Section == '1' %}
                             <img style="width: 33%" class="img-fluid" src="{{ img.photo.url }}" alt="{{ img.title }}">
                         {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
</div>

    <div class="container">
    <div class="col-10 justify-content-center  mt-4" style="width: 100%">
        <div class="subSecciones" style="margin-top: 30px;">
            <div style="margin-bottom: 20px;">
            <a href="#" class="btn-Sub">Actividades</a>
            <p style="margin-top: 10px;font-weight: 700;">Descubre nuestras actividades</p>
            </div>
                <div class="d-flex justify-content-between">
                    {% for img in photos_gallery %}
                         {% if img.Section == '2' %}
                             <img style="width: 33%" class="img-fluid" src="{{ img.photo.url }}" alt="{{ img.title }}">
                         {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
</div>

    <div class="container col-10">
    <div class="d-flex  mt-4" style="width: 100%" >
        <div class="subSecciones" style="margin-top: 30px;">
            <div style="margin-bottom: 20px;">
            <a href="amenazas.html" class="btn-Sub">Amenazas</a>
            <p style="margin-top: 10px;font-weight: 700;">Conoce las amenazas que nos afectan</p>
            </div>
                <div  class="d-flex justify-content-between">
                    {% for img in photos_gallery %}
                         {% if img.Section == '3' %}
                             <img style="width: 33%" class="img-fluid" src="{{ img.photo.url }}" alt="{{ img.title }}">
                         {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
</div>

    <div class="col-10 d-flex justify-content-center " style="width: 100%">
    <div >
        <h1 style="color: #198754 ;margin-top: 50px" >Flora y Fauna</h1>
    </div>
    </div>



    <div class="container" style="width: 100%">
        <div class="col-10 d-flex justify-content-center  mt-4" style="width: 100%" >
            <div class="col-10">
                  <div  class="d-flex justify-content-between">
                      {% for i in floraView %}
                          <div class="card">
                            <a href="#" style="text-decoration: none;">
                                <img style="width: 100%;" class="gallery-item" src="{{ i.photo.url }}" alt="{{ i.title }}">
                                    <div class="card-content">
                                        <h3 class="card-title" style="color: #198754;">{{ i.title }}</h3>
                                        <p class="card-description">{{ i.description }}</p>
                                    </div>
                            </a>
                          </div>
                      {% endfor %}
                  </div>
            </div>
        </div>
    </div>


{% endblock %}